name: CI Training - Indonesian Job Classifier

on:
  push:
    branches: [main]
    paths:
      - 'MLProject/**'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  train-and-build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MLflow and dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 dagshub scikit-learn pandas numpy matplotlib nltk

      - name: Run MLflow Project training
        shell: powershell
        run: |
          cd MLProject
          python modelling.py --dataset jobs_preprocessing.csv --max_features 5000 --C 1.0 --max_iter 1000

      - name: Show training results
        shell: powershell
        run: |
          if (Test-Path "MLProject\mlflow_run_id.txt") {
            $RUN_ID = Get-Content "MLProject\mlflow_run_id.txt"
            echo "Training berhasil. Run ID: $RUN_ID"
          } else {
            echo "Training completed successfully."
          }
